# Generated by Django 5.2 on 2025-04-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
