# Generated by Django 5.2 on 2025-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_calculo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculo',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculo',
            name='median',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculo',
            name='status',
            field=models.TextField(default='Processando'),
        ),
    ]
