# Generated by Django 5.2 on 2025-04-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_calculo_average_alter_calculo_median_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calculo',
            table='Processamento',
        ),
    ]
